services:
  tldwbot:
    build: .
    container_name: tldwbot
    env_file: .env
    restart: unless-stopped
    volumes:
      - .:/app
      - ./data:/app/data
    network_mode: host
    extra_hosts:
      - "host.docker.internal:host-gateway"

    # Uncomment the following to enable GPU passthrough for local Whisper acceleration
    # Requires NVIDIA Container Toolkit: https://github.com/NVIDIA/nvidia-container-toolkit
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
